(in-package "ACL2")

;; (include-book "ExtCodeSizeAddressInputTooBigLeftMyAddress")
;; (include-book "ExtCodeSizeAddressInputTooBigRightMyAddress")
;; (include-book "address0")
;; (include-book "address1")
;; (include-book "balance0")
;; (include-book "balance01")
;; (include-book "balance1")
;; (include-book "balanceAddress2")
;; (include-book "balanceAddressInputTooBig")
;; (include-book "balanceAddressInputTooBigLeftMyAddress")
;; (include-book "balanceAddressInputTooBigRightMyAddress")
;; (include-book "balanceCaller3")
(include-book "caller")
(include-book "callvalue")
;; (include-book "origin")
