(in-package "ACL2")

(include-book "dup1")
(include-book "dup10")
(include-book "dup11")
(include-book "dup12")
(include-book "dup13")
(include-book "dup14")
(include-book "dup15")
(include-book "dup16")
(include-book "dup2")
(include-book "dup3")
(include-book "dup4")
(include-book "dup5")
(include-book "dup6")
(include-book "dup7")
(include-book "dup8")
(include-book "dup9")
(include-book "push1")
(include-book "push10")
(include-book "push11")
(include-book "push12")
(include-book "push13")
(include-book "push14")
(include-book "push15")
(include-book "push16")
(include-book "push17")
(include-book "push18")
(include-book "push19")
(include-book "push1_missingStack")
(include-book "push2")
(include-book "push20")
(include-book "push21")
(include-book "push22")
(include-book "push23")
(include-book "push24")
(include-book "push25")
(include-book "push26")
(include-book "push27")
(include-book "push28")
(include-book "push29")
(include-book "push3")
(include-book "push30")
(include-book "push31")
(include-book "push32")
;; (include-book "push32AndSuicide")
(include-book "push32FillUpInputWithZerosAtTheEnd")
(include-book "push32Undefined")
(include-book "push32Undefined2")
(include-book "push32Undefined3")
(include-book "push4")
(include-book "push5")
(include-book "push6")
(include-book "push7")
(include-book "push8")
(include-book "push9")
;; (include-book "swap1")
;; (include-book "swap10")
;; (include-book "swap11")
;; (include-book "swap12")
;; (include-book "swap13")
;; (include-book "swap14")
;; (include-book "swap15")
;; (include-book "swap16")
;; (include-book "swap2")
;; (include-book "swap3")
;; (include-book "swap4")
;; (include-book "swap5")
;; (include-book "swap6")
;; (include-book "swap7")
;; (include-book "swap8")
;; (include-book "swap9")
(include-book "swapjump1")
